### PR TITLE
Design Revisions

### PR DESCRIPTION
**Pull request by nchan0154**

### CODE REVIEW

**Comment by marcoow** [comment]
The arrows in links move slightly on hover (this is in Safari):

image


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1268 x 695 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1268x695&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c3f1668de3b286431f582&resolution=resolved)

**Comment by marcoow** [comment]
The text overlay appears over the menu on mobile:

image

<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1196 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1196x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c3f7f7bef622994279511&resolution=resolved)

**Comment by marcoow** [comment]
Can we use `cursor: pointer;` for the _"x"_?

image
<details><summary>Browser metadata</summary>





```
Path:      /contact/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fcontact%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/contact/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c3ff0cdcd8128bc8a90a7&resolution=resolved)

**Comment by marcoow** [comment]
Also we'd need a submitting state for the form so we a) make clear the message is being sent, b) disable further input during that time
<details><summary>Browser metadata</summary>





```
Path:      /contact/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fcontact%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/contact/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c4024ef99212cbf30f514&resolution=resolved)

**Comment by marcoow** [comment]
image

The popover should also indicate the current page (in this case _"Digital Products"_)
<details><summary>Browser metadata</summary>





```
Path:      /services/digital-products/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fservices%2Fdigital-products%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/services/digital-products/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c40da7bef622da12793ba&resolution=resolved)

**Comment by marcoow** [comment]
The bottom of the _"g"_ is visible jus a bit:

image
<details><summary>Browser metadata</summary>





```
Path:      /services/training/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fservices%2Ftraining%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/services/training/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c414f19b2c32e0cb035af&resolution=resolved)

**Comment by marcoow** [comment]
Should this show 9 entries on the second page so the grid is complete?

Also, can we make this scrollable horizontally as well so clicking the arrow button is optional?

image
<details><summary>Browser metadata</summary>





```
Path:      /work/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fwork%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/work/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c41a63dd9f22c90f1c93c&resolution=resolved)

**Comment by marcoow** [comment]
I'd rather have screenshots of the browser app on this page instead of the mobile app and parts of a UI
<details><summary>Browser metadata</summary>





```
Path:      /cases/qonto/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fcases%2Fqonto%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/cases/qonto/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c421d179eee339bdb2373&resolution=resolved)

**Comment by marcoow** [comment]
Should we make the entire boxed clickable?

image
<details><summary>Browser metadata</summary>





```
Path:      /ember-consulting/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fember-consulting%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/ember-consulting/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c428c18071f325a6836c4&resolution=resolved)

**Comment by marcoow** [comment]
This link doesn't work (should jump to the download section below)

image
<details><summary>Browser metadata</summary>





```
Path:      /playbook/#download
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fplaybook%2F%23download&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/playbook/#download) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c42e248f3d530045eaa9b&resolution=resolved)

**Comment by marcoow** [comment]
Should these boxes all have the same height?

image


<details><summary>Browser metadata</summary>





```
Path:      /resources/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fresources%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/resources/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c432a72bf8531fde6c7b3&resolution=resolved)

**Comment by marcoow** [comment]
image

The link doesn't lead to the event
<details><summary>Browser metadata</summary>





```
Path:      /talks/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Ftalks%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/talks/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c4379cdcd812fc58a2c60&resolution=resolved)

**Comment by marcoow** [comment]
Can we remove this if there's no previous page?

image
<details><summary>Browser metadata</summary>





```
Path:      /blog/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fblog%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/blog/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c444f5cc2c6325575b630&resolution=resolved)

**Comment by marcoow** [comment]
I'm @marcoow here btw

**Comment by marcoow** [comment]
This horizontal line isn't in the latest designs:

image
<details><summary>Browser metadata</summary>





```
Path:      /blog/2021/07/13/effective-infrastructure-for-efficient-development-workflows/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fblog%2F2021%2F07%2F13%2Feffective-infrastructure-for-efficient-development-workflows%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/blog/2021/07/13/effective-infrastructure-for-efficient-development-workflows/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c7029a4cc2a5e0f7e27c3&resolution=resolved)

**Comment by marcoow** [comment]
Can we add some content to the calendar? See the latest content we have on the live site: https://simplabs.com/calendar/
<details><summary>Browser metadata</summary>





```
Path:      /calendar/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fcalendar%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/calendar/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c7070786b7e6393636e96&resolution=resolved)

**Comment by marcoow** [comment]
The "Services" and "Work" titles should be links as well:

image
<details><summary>Browser metadata</summary>





```
Path:      /privacy/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fprivacy%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/privacy/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c72002561b669282f2917&resolution=resolved)

**Comment by marcoow** [comment]
On the experts insights page, there seems to be a bunch of unnecessary whitespace at the bottom?

image
<details><summary>Browser metadata</summary>





```
Path:      /privacy/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1182 x 688 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fprivacy%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1182x688&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/privacy/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623c74dd1ec06870cd597568&resolution=resolved)

**Comment by pichfl** [comment]
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/nic/reviewers)

**Comment by pichfl** [comment]
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/nic/reviewers)

**Comment by pichfl** [comment]
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/nic/reviewers)

**Comment by nchan0154** [comment]
> image
> 
> Given we play with overlapping elements a lot on the page, it strikes me as odd that there is such a visual gap between the main navigation and the flyout menu.
> 
> I noticed a few edge cases as well:
> 
> * hovering the navigation item in its active state hides the yellow indication. While not "wrong", it feels a bit clunky.
> * There is no way to reach navigation items in the menus through keyboard navigation. The triggers can be focussed, but there is none of the expected interaction options, tabbing switches to the next menu.
> 
> Browser metadata
> ```
> Path:      /
> Browser:   Safari 15.4 on Mac OS 10.15.7
> Viewport:  1457 x 1242 @2x
> Language:  de-DE
> Cookies:   Disabled
> ```
> 
> [Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1457x1242&speed=1&start=true&ref=netlify-source)
> 
> [Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623abf381229a1000974e125&commentID=623ca08e39767800abc17f83&resolution=resolved)

@pichfl Can I get a little bit more detail on how you're testing keyboard navigation? For me, when the parent links are focused, I can tab through the child navigation items.

**Comment by pichfl** [comment]
> > I noticed a few edge cases as well:
> > 
> > * hovering the navigation item in its active state hides the yellow indication. While not "wrong", it feels a bit clunky.
> > * There is no way to reach navigation items in the menus through keyboard navigation. The triggers can be focussed, but there is none of the expected interaction options, tabbing switches to the next menu.
> 
> @pichfl Can I get a little bit more detail on how you're testing keyboard navigation? For me, when the parent links are focused, I can tab through the child navigation items.

I checked again today (same browser and everything) and it seems to work now. Not sure what was going on, I didn't change things. I think we can ignore this then.

**Comment by pichfl** [comment]
Alright! Had a quick call with Linda to discuss feedback.

###  Regarding the Ember logo / banner

Linda will provide an updated version. We decided to use the regular Ember logo without the rectangle around which actually solves the visual imbalance next to the diagonal.

### Regarding the navigation

Please check in Safari and Firefox. `backdrop-filter: blur` does not seem to work there. Consider using `@supports` in CSS, falling back to a plain white navigation bar in browsers that do not support the backdrop thing. This is important for readability and usability of the navigation.

### Regarding the navigation dropdowns

Please move the dropdowns up by -20px, making them overlap the navigation bar. (I used the web inspector, adding `margin-top: -20px;` to `.nav-dropdown__list` seemed to do the trick)

Please use a wider drop shadow for the dropdowns so they appear on a different visual layer as well, after discussion with Lina we suggest `box-shadow: 0 0.25rem 0.6rem rgba(0,0,0,0.5)`;


### Dropdowns in Safari

Please double check the navigation in Safari, while tabbing works for me now, I can no longer click the navigation items to open the dropdown.
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1715 x 1242 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1715x1242&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623d72950681af0008396e52&commentID=623dcdd1f629a101a11def1e&resolution=resolved)

**Comment by nchan0154** [comment]
@pichfl Sorry for the trouble, I think you caught me in the middle of trying to isolate some behavior on Safari. I run Windows so I had made some tweaks for easier debugging on Browserstack. All should be resolved now, please let me know.

@marcoow All of your feedback should be incorporated, including current calendar events.

**Comment by marcoow** [comment]
> Also, can we make this scrollable horizontally as well so clicking the arrow button is optional?

I really think the "Meet our Clients" section should be scrollable horizontally. On the desktop that's really what I want and having to click the arrows in an annoyance (I understand we need them for people without trackpads who cannot scroll horizontally).

**Comment by marcoow** [comment]
This looks a bit strange… I think we should make it so that the arrow can never break into a new line on its own?

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /services/digital-products/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1293 x 713 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fservices%2Fdigital-products%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1293x713&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/services/digital-products/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=624159f4f93c7c0008eee0d0&commentID=62431e04c369582511474f3b&resolution=resolved)

**Comment by marcoow** [comment]
I think these should have `cursor: pointer;`?

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /work/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1293 x 713 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fwork%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1293x713&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/work/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=624159f4f93c7c0008eee0d0&commentID=62431f26e013151b093f4d15&resolution=resolved)

**Comment by marcoow** [comment]
"CPO" :)
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /cases/qonto/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1293 x 713 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fcases%2Fqonto%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1293x713&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/cases/qonto/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=624159f4f93c7c0008eee0d0&commentID=62431f6529733f1583df3e56&resolution=resolved)

**Comment by marcoow** [comment]
Should there be a bit of horizontal space between the 2 images?

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /resources/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1312 x 812 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fresources%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1312x812&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/resources/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=624159f4f93c7c0008eee0d0&commentID=62432045c3695828eb474e70&resolution=resolved)

**Comment by marcoow** [comment]
I know this horizontal line is in the designs but I don't feel we need it and it doesn't seem to fit in particularly well? What do you think @lindaguerrisi ?

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /blog/
Browser:   Safari 15.4 on Mac OS 10.15.7
Viewport:  1355 x 812 @2x
Language:  de-DE
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--mainmatter-wip.netlify.app%2Fblog%2F&os=OS%20X&os_version=Catalina&browser=Safari&browser_version=15.0&resolution=1355x812&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/blog/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=624159f4f93c7c0008eee0d0&commentID=6243213a4a1715212b934931&resolution=resolved)

**Comment by marcoow** [comment]
"Why Mainmatter" doesn't seem to break nicely on mobile (iPhone 13 mini in this case):

IMG_0586

**Comment by marcoow** [comment]
Imprint and privacy policy flow too wide on mobile (iPhone 13 mini in this case):

IMG_0587
IMG_0588

**Comment by marcoow** [comment]
I'm not sure that's intentional or a bug but it looks like the top menu isn't sticky on the blog pages?

**Comment by nchan0154** [comment]
> > Also, can we make this scrollable horizontally as well so clicking the arrow button is optional?
> 
> I really think the "Meet our Clients" section should be scrollable horizontally. On the desktop that's really what I want and having to click the arrows in an annoyance (I understand we need them for people without trackpads who cannot scroll horizontally).

@marcoow Can you elaborate what you mean by this? Do you mean for the section to be like the logo wall on the homepage? Right now it's a carousel with drag enabled so it is possible to scroll through them without using the arrows.

@lindaguerrisi can you also weigh in on these design questions as well? 
> These don't seem to be aligned correctly on the left?
> 
> screenshot

In the designs the text is aligned, and links with backgrounds have the background extending beyond the container.  Please let me know what the desired behavior should be!


> I'm not sure that's intentional or a bug but it looks like the top menu isn't sticky on the blog pages?

Linda called out some pages to have the sticky nav disabled, can you help explain?

**Comment by marcoow** [comment]
> Right now it's a carousel with drag enabled so it is possible to scroll through them without using the arrows.

Ah, didn't try dragging :) I think horizontal scrolling would be much nicer than dragging tbh. We can still keep the arrows as well of course.

**Comment by marcoow** [comment]
> Linda called out some pages to have the sticky nav disabled, can you help explain? It's just an option I can turn on and off so please let me know what the desired outcome is.

I guess it makes sense on the blog… If it was intentional I'd say all good, just wasn't aware 👍

**Comment by lindaguerrisi** [comment]
> We typically have the arrows in links flow with the text but in these boxes it flows independently of the text – should we align on one (I think making it flow with the text looks better)? What do you think @lindaguerrisi ?
> 
> screenshot
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-3--mainmatter-wip.netlify.app/services/product-design/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=624159f4f93c7c0008eee0d0&commentID=62431eb42ebb9214adcff781&resolution=resolved)

I think it's the way the button is developed. If we can find a way to have the arrow flowing the text it's definitely better!

**Comment by lindaguerrisi** [comment]
> > > Also, can we make this scrollable horizontally as well so clicking the arrow button is optional?
> > 
> > 
> > I really think the "Meet our Clients" section should be scrollable horizontally. On the desktop that's really what I want and having to click the arrows in an annoyance (I understand we need them for people without trackpads who cannot scroll horizontally).
> 
> @marcoow Can you elaborate what you mean by this? Do you mean for the section to be like the logo wall on the homepage? Right now it's a carousel with drag enabled so it is possible to scroll through them without using the arrows.
> 
> @lindaguerrisi can you also weigh in on these design questions as well?
> 
> > These don't seem to be aligned correctly on the left?
> > screenshot
> 
> In the designs the text is aligned, and links with backgrounds have the background extending beyond the container. Please let me know what the desired behavior should be!
> 
> > I'm not sure that's intentional or a bug but it looks like the top menu isn't sticky on the blog pages?
> 
> Linda called out some pages to have the sticky nav disabled, can you help explain? It's just an option I can turn on and off so please let me know what the desired outcome is.

@nchan0154 about the "meet our clients" I agree we should include also the horizontal scroll if we can, the same way we have it for the video interviews. 
@marcoow  I have thought of not having the navigation pinned in the blog posts only, it really doesn't help readability when I am going through a content heavy page and I would like to leave it like this unless we have a different opinion?

**Comment by marcoow** [comment]
> @marcoow I have thought of not having the navigation pinned in the blog posts only, it really doesn't help readability when I am going through a content heavy page and I would like to leave it like this unless we have a different opinion?

yes, makes sense to me – just wasn't aware and wanted to confirm it was actually intentional.

**Comment by nchan0154** [comment]
@marcoow @lindaguerrisi 
Deploy updated with latest changes.
I've contemplated the horizontal scrolling for the client work grid and I think to develop something with the current presentation + horizontal scrolling, there are some complexities here that would mean a lot of time and energy developing a custom component. I've outlined requirements below:

- Right now we're using a carousel library to control this section, the carousel library requires each 'slide' to be its own seperate element (so each slide has 9 grid items)
- Because each slide is it's own grid and we do not have CSS subgrid, [the grids don't line up with eachother](https://user-images.githubusercontent.com/12852862/160956450-97b05059-9651-4903-8b0d-b65ccc09f0fe.PNG)
- To make all the cards correctly aligned, they need to be children of a single grid parent, and we could use CSS scroll snap to ensure scrolling lines up to each grid view
- In the current display, we force a maximum of 9 grid items to be displayed. Because the cards do not visually overflow and are neatly placed in a fixed grid with discrete 'views', the logical reading order for me would be 1-9 on the first view, then 1-9 on the second, and finally the remaining items on the third. We would need to manipulate both the order of grid items to match the current display and render out of view list items as inert, and update this with JS on view changes.
- Arrows need to be correctly disabled, be updated to reflect state when scrolling without arrows, need to calculate where to jump to, etc.
- Scroll snap is not supported in Firefox

If you feel like this is the best possible solution for this section, let me know and I can adjust scope, but I wanted to double check first before I spent a week+ worth of hours on something without clarifying the requirements :) I think that stripping back a few requirements or altering the presentation a bit makes this a substantially less tricky component, so let me know what is essential. For example, if this section is in one row, or if the cards are fixed with and overflow like the video cards do, then a more logical reading order would be all of the first row, then all of the second, etc, and arrows/scroll snap wouldn't be neccessary either.

On a related tangent, I'm very much loathe to remove scrollbars anywhere as it means I cannot use the interface as my pointer device does not have a scroll wheel 😂  If you feel strongly about this let me know.

**Comment by marcoow** [comment]
Hm, not entirely sure I understand all of this. I thought this would be just one big grid (instead of 3 separate grids with each max 9 items) and clicking the arrow buttons would simply scroll to a particular offset? I think we could make this work without scroll snapping also so that you can just scroll to any position (and clicking on any of the buttons would simplabs take you to the next position where one of the columns starts)?

**Comment by nchan0154** [comment]
@marcoow Thank you, that reply helps me understand what you are thinking! 🙌  Did you want each card item to be a fixed size (so there may be some items cut off as an affordance to help the user know to scroll, like the expert insight cards on the resources page), or more like how it is now? Also, did you want the container to extend all the way to the right side of the screen, or stay centered?

**Comment by marcoow** [comment]
I'd expect:

* all items have the same height (not fixed though) so that the highest item in a row determines the height of all others (independently of whether it's currently visible or not)
* the container to be centered but the grid inside of the container to be laid out so that it allows for 3 columns to be visible at a time as it is now as long as the current horizontal scroll position is exactly at the beginning of one of the columns (then you should see that column plus the 2 following ones)

**Comment by nchan0154** [comment]
@marcoow Great, the clarification helped a lot! I've made updates to the work grid.

**Comment by marcoow** [comment]
Cool, looks good – just 2 things:

* It seems this sets the vertical scrolling position to 0 when you click the arrow buttons so that you always end at the top of the list again (and the buttons are out of sight)? That seems a bit confusing.

**Comment by nchan0154** [comment]
@marcoow 
Oh yes, this was requested in an earlier round of feedback but I can remove it!

**Comment by marcoow** [comment]
I think that was a misunderstanding probabyl

**Pull request closed without merging**
